CREATE ROLE "CRM_USER" LOGIN PASSWORD 'CRM_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "BILLING_USER" LOGIN PASSWORD 'BILLING_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "COLLECTION_USER" LOGIN PASSWORD 'COLLECTION_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "ORDERS_USER" LOGIN PASSWORD 'ORDERS_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_CRM_USER" LOGIN PASSWORD 'TAR_CRM_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_BILLING_USER" LOGIN PASSWORD 'TAR_BILLING_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_COLLECTION_USER" LOGIN PASSWORD 'TAR_COLLECTION_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;
CREATE ROLE "TAR_ORDERS_USER" LOGIN PASSWORD 'TAR_ORDERS_USER' SUPERUSER INHERIT CREATEDB CREATEROLE REPLICATION;